#!/usr/bin/env bash
# ==============================================================================
# Dovecot IMAP Automated Setup & Installer Script (SQLite Edition)
# For Ubuntu / Debian Linux VPS
# ==============================================================================

set -e

echo "=========================================================="
echo "🚀 Starting Dovecot IMAP Server Setup (SQLite)"
echo "=========================================================="

# Check root privilege
if [ "$EUID" -ne 0 ]; then
  echo "❌ Please run this script as root or with sudo:"
  echo "   sudo bash backend/imap-setup/setup-dovecot.sh"
  exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
echo "📂 Project Root: ${PROJECT_ROOT}"

SQLITE_DB_PATH="${PROJECT_ROOT}/backend/storage/email_logs.sqlite"

# 1. Install Dovecot packages with SQLite driver
echo "📦 Installing Dovecot IMAP and SQLite driver..."
apt update -y
apt install -y dovecot-imapd dovecot-sqlite

# 2. Create vmail user and group if not exist
if ! id "vmail" &>/dev/null; then
    echo "👤 Creating vmail user (uid/gid 5000)..."
    groupadd -g 5000 vmail || true
    useradd -u 5000 -g vmail -s /usr/sbin/nologin -d /var/mail vmail || true
fi

# 3. Ensure Maildir and Storage directories exist and have proper permissions
MAILDIR_PATH="${PROJECT_ROOT}/backend/storage/maildir"
STORAGE_PATH="${PROJECT_ROOT}/backend/storage"
echo "📁 Ensuring Maildir directory exists: ${MAILDIR_PATH}"
mkdir -p "${MAILDIR_PATH}"
mkdir -p "${STORAGE_PATH}"
chmod -R 777 "${MAILDIR_PATH}"
chmod 777 "${STORAGE_PATH}"
if [ -f "${SQLITE_DB_PATH}" ]; then
  chmod 666 "${SQLITE_DB_PATH}"
fi

# 4. Generate dynamic dovecot.conf with absolute paths
echo "⚙️ Configuring /etc/dovecot/dovecot.conf..."
cat << EOF > /etc/dovecot/dovecot.conf
# Auto-generated by Email Server VPS setup script
protocols = imap
listen = *, ::
base_dir = /var/run/dovecot/
auth_mechanisms = plain login
disable_plaintext_auth = no
auth_verbose = yes

mail_location = maildir:${MAILDIR_PATH}/%d/%n:LAYOUT=fs:DIRNAME=.

namespace inbox {
  inbox = yes
  separator = /
}

# IMAP & IMAPS Ports
service imap-login {
  inet_listener imap {
    port = 143
  }
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}

passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}
EOF

# 5. Generate dynamic dovecot-sql.conf.ext for SQLite
echo "⚙️ Configuring /etc/dovecot/dovecot-sql.conf.ext for SQLite..."
cat << EOF > /etc/dovecot/dovecot-sql.conf.ext
driver = sqlite
connect = ${SQLITE_DB_PATH}
default_pass_scheme = PLAIN

password_query = SELECT email AS user, COALESCE(plain_password, password_hash) AS password FROM mailbox_table WHERE LOWER(email) = LOWER('%u')
user_query = SELECT 5000 AS uid, 5000 AS gid, '${MAILDIR_PATH}/%d/%n' AS home, 'maildir:${MAILDIR_PATH}/%d/%n:LAYOUT=fs:DIRNAME=.' AS mail FROM mailbox_table WHERE LOWER(email) = LOWER('%u')
iterate_query = SELECT email AS user FROM mailbox_table
EOF

chmod 600 /etc/dovecot/dovecot-sql.conf.ext

# 6. Allow IMAP ports in UFW Firewall if UFW is active
if command -v ufw &> /dev/null; then
    echo "🛡️ Configuring Firewall (UFW) for Ports 143 and 993..."
    ufw allow 143/tcp || true
    ufw allow 993/tcp || true
fi

# 7. Restart and enable Dovecot service
echo "🔄 Restarting Dovecot service..."
systemctl restart dovecot || service dovecot restart
systemctl enable dovecot || true

echo ""
echo "=========================================================="
echo "✅ Dovecot IMAP Setup Complete with SQLite!"
echo "   - Database: SQLite (${SQLITE_DB_PATH})"
echo "   - IMAP Port: 143 (Plain/STARTTLS)"
echo "   - IMAPS Port: 993 (SSL)"
echo "   - Maildir: ${MAILDIR_PATH}"
echo "=========================================================="
